//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceRestSMS.WF_SMSNacido {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WF_SMSNacido.IStartSMSNacido")]
    public interface IStartSMSNacido {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStartSMSNacido/StartSMSNacido", ReplyAction="http://tempuri.org/IStartSMSNacido/StartSMSNacidoResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="p_instanciaId")]
        string StartSMSNacido(int p_mes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStartSMSNacido/StartSMSNacido", ReplyAction="http://tempuri.org/IStartSMSNacido/StartSMSNacidoResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="p_instanciaId")]
        System.Threading.Tasks.Task<string> StartSMSNacidoAsync(int p_mes);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStartSMSNacidoChannel : ServiceRestSMS.WF_SMSNacido.IStartSMSNacido, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StartSMSNacidoClient : System.ServiceModel.ClientBase<ServiceRestSMS.WF_SMSNacido.IStartSMSNacido>, ServiceRestSMS.WF_SMSNacido.IStartSMSNacido {
        
        public StartSMSNacidoClient() {
        }
        
        public StartSMSNacidoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StartSMSNacidoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StartSMSNacidoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StartSMSNacidoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string StartSMSNacido(int p_mes) {
            return base.Channel.StartSMSNacido(p_mes);
        }
        
        public System.Threading.Tasks.Task<string> StartSMSNacidoAsync(int p_mes) {
            return base.Channel.StartSMSNacidoAsync(p_mes);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WF_SMSNacido.StopSMSNacido")]
    public interface StopSMSNacido {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/StopSMSNacido/StopSMSNacido")]
        void StopSMSNacido(string p_instanciaId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/StopSMSNacido/StopSMSNacido")]
        System.Threading.Tasks.Task StopSMSNacidoAsync(string p_instanciaId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StopSMSNacidoChannel : ServiceRestSMS.WF_SMSNacido.StopSMSNacido, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StopSMSNacidoClient : System.ServiceModel.ClientBase<ServiceRestSMS.WF_SMSNacido.StopSMSNacido>, ServiceRestSMS.WF_SMSNacido.StopSMSNacido {
        
        public StopSMSNacidoClient() {
        }
        
        public StopSMSNacidoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StopSMSNacidoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StopSMSNacidoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StopSMSNacidoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void StopSMSNacido(string p_instanciaId) {
            base.Channel.StopSMSNacido(p_instanciaId);
        }
        
        public System.Threading.Tasks.Task StopSMSNacidoAsync(string p_instanciaId) {
            return base.Channel.StopSMSNacidoAsync(p_instanciaId);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WF_SMSNacido.RespSMSControl")]
    public interface RespSMSControl {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/RespSMSControl/RespSMSControl")]
        void RespSMSControl(string p_instanciaId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/RespSMSControl/RespSMSControl")]
        System.Threading.Tasks.Task RespSMSControlAsync(string p_instanciaId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RespSMSControlChannel : ServiceRestSMS.WF_SMSNacido.RespSMSControl, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RespSMSControlClient : System.ServiceModel.ClientBase<ServiceRestSMS.WF_SMSNacido.RespSMSControl>, ServiceRestSMS.WF_SMSNacido.RespSMSControl {
        
        public RespSMSControlClient() {
        }
        
        public RespSMSControlClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RespSMSControlClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RespSMSControlClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RespSMSControlClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void RespSMSControl(string p_instanciaId) {
            base.Channel.RespSMSControl(p_instanciaId);
        }
        
        public System.Threading.Tasks.Task RespSMSControlAsync(string p_instanciaId) {
            return base.Channel.RespSMSControlAsync(p_instanciaId);
        }
    }
}
