//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceRestSMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogMensajeControl
    {
        public long ID { get; set; }
        public string ID_INSTANCIA { get; set; }
        public int ID_TRANSACCION { get; set; }
        public byte ID_RESPUESTA { get; set; }
        public System.DateTime FECHA { get; set; }
        public int MES { get; set; }
    
        public virtual TipoRespuestaControl TipoRespuestaControl { get; set; }
    }
}
