//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceRestSMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogMensaje
    {
        public long ID { get; set; }
        public System.DateTime FECHA { get; set; }
        public string MENSAJE { get; set; }
        public byte ID_TIPOMENSAJE { get; set; }
    
        public virtual TipoMensaje TipoMensaje { get; set; }
    }
}
