//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceRestSMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProgMilDiasEntities : DbContext
    {
        public ProgMilDiasEntities()
            : base("name=ProgMilDiasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<logMensajeEnviado> logMensajeEnviado { get; set; }
        public virtual DbSet<logMensajeRecibido> logMensajeRecibido { get; set; }
        public virtual DbSet<logNotificacion> logNotificacion { get; set; }
        public virtual DbSet<logSMSError> logSMSError { get; set; }
    }
}
