//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceRestSMS.WF_SMSGestacion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WF_SMSGestacion.IStartSMSGestacion")]
    public interface IStartSMSGestacion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStartSMSGestacion/StartSMSGestacion", ReplyAction="http://tempuri.org/IStartSMSGestacion/StartSMSGestacionResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="p_embarazadaId")]
        string StartSMSGestacion(int p_mes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStartSMSGestacion/StartSMSGestacion", ReplyAction="http://tempuri.org/IStartSMSGestacion/StartSMSGestacionResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="p_embarazadaId")]
        System.Threading.Tasks.Task<string> StartSMSGestacionAsync(int p_mes);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStartSMSGestacionChannel : ServiceRestSMS.WF_SMSGestacion.IStartSMSGestacion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StartSMSGestacionClient : System.ServiceModel.ClientBase<ServiceRestSMS.WF_SMSGestacion.IStartSMSGestacion>, ServiceRestSMS.WF_SMSGestacion.IStartSMSGestacion {
        
        public StartSMSGestacionClient() {
        }
        
        public StartSMSGestacionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StartSMSGestacionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StartSMSGestacionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StartSMSGestacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string StartSMSGestacion(int p_mes) {
            return base.Channel.StartSMSGestacion(p_mes);
        }
        
        public System.Threading.Tasks.Task<string> StartSMSGestacionAsync(int p_mes) {
            return base.Channel.StartSMSGestacionAsync(p_mes);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WF_SMSGestacion.StopSMSGestacion")]
    public interface StopSMSGestacion {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/StopSMSGestacion/StopSMSGestacion")]
        void StopSMSGestacion(string p_embarazadaId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/StopSMSGestacion/StopSMSGestacion")]
        System.Threading.Tasks.Task StopSMSGestacionAsync(string p_embarazadaId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StopSMSGestacionChannel : ServiceRestSMS.WF_SMSGestacion.StopSMSGestacion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StopSMSGestacionClient : System.ServiceModel.ClientBase<ServiceRestSMS.WF_SMSGestacion.StopSMSGestacion>, ServiceRestSMS.WF_SMSGestacion.StopSMSGestacion {
        
        public StopSMSGestacionClient() {
        }
        
        public StopSMSGestacionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StopSMSGestacionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StopSMSGestacionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StopSMSGestacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void StopSMSGestacion(string p_embarazadaId) {
            base.Channel.StopSMSGestacion(p_embarazadaId);
        }
        
        public System.Threading.Tasks.Task StopSMSGestacionAsync(string p_embarazadaId) {
            return base.Channel.StopSMSGestacionAsync(p_embarazadaId);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WF_SMSGestacion.RespSMSControl")]
    public interface RespSMSControl {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/RespSMSControl/RespSMSControl")]
        void RespSMSControl(string p_embarazadaId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/RespSMSControl/RespSMSControl")]
        System.Threading.Tasks.Task RespSMSControlAsync(string p_embarazadaId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RespSMSControlChannel : ServiceRestSMS.WF_SMSGestacion.RespSMSControl, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RespSMSControlClient : System.ServiceModel.ClientBase<ServiceRestSMS.WF_SMSGestacion.RespSMSControl>, ServiceRestSMS.WF_SMSGestacion.RespSMSControl {
        
        public RespSMSControlClient() {
        }
        
        public RespSMSControlClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RespSMSControlClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RespSMSControlClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RespSMSControlClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void RespSMSControl(string p_embarazadaId) {
            base.Channel.RespSMSControl(p_embarazadaId);
        }
        
        public System.Threading.Tasks.Task RespSMSControlAsync(string p_embarazadaId) {
            return base.Channel.RespSMSControlAsync(p_embarazadaId);
        }
    }
}
